FROM pgvector/pgvector:pg17-trixie

ENV POSTGRES_DB=vectordb
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password123
ENV POSTGRES_HOST_AUTH_METHOD=md5

EXPOSE 5432

RUN mkdir -p /docker-entrypoint-initdb.d
RUN echo "CREATE EXTENSION IF NOT EXISTS vector;" > /docker-entrypoint-initdb.d/01-create-extension.sql

WORKDIR /var/lib/postgresql/data