CREATE TABLE "documents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_name" text,
  "document_author" text,
  "document_year" int,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "chunks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" int,
  "chunk_text" text,
  "page_number" int,
  "embedding" vector(768)
);

CREATE TABLE "entities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE,
  "entities_description" text
);

CREATE TABLE "relations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "src_entity_id" int,
  "dst_entity_id" int,
  "relation" text,
  "chunk_id" int
);

ALTER TABLE "chunks" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id");

ALTER TABLE "relations" ADD FOREIGN KEY ("src_entity_id") REFERENCES "entities" ("id");

ALTER TABLE "relations" ADD FOREIGN KEY ("dst_entity_id") REFERENCES "entities" ("id");

ALTER TABLE "relations" ADD FOREIGN KEY ("chunk_id") REFERENCES "chunks" ("id");
